### ISSUE TITLE
.env

### ISSUE THREAD

**Issue by MazenSiraj** [alejandro-ao/langchain-ask-csv#3]
Please update the .env file I am not able to download it 
all dependencies have errors, internal ones

  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      Traceback (most recent call last):
        File "C:\Users\MAM019\Desktop\langchain-ask-csv-main\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>        
          main()
        File "C:\Users\MAM019\Desktop\langchain-ask-csv-main\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\MAM019\Desktop\langchain-ask-csv-main\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\MAM019\AppData\Local\Temp\pip-build-env-l7c8ffe9\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel     
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\MAM019\AppData\Local\Temp\pip-build-env-l7c8ffe9\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\MAM019\AppData\Local\Temp\pip-build-env-l7c8ffe9\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\MAM019\AppData\Local\Temp\pip-build-env-l7c8ffe9\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 55, in <module>
      RuntimeError:

      Starting with v0.37.0, the 'azure-storage' meta-package is deprecated and cannot be installed anymore.
      Please install the service specific packages prefixed by `azure` needed for your application.

      The complete list of available packages can be found at:
      https://aka.ms/azsdk/python/all

      Here's a non-exhaustive list of common packages:

      - [azure-storage-blob](https://pypi.org/project/azure-storage-blob) : Blob storage client
      - [azure-storage-file-share](https://pypi.org/project/azure-storage-file-share) : Storage file share client
      - [azure-storage-file-datalake](https://pypi.org/project/azure-storage-file-datalake) : ADLS Gen2 client
      - [azure-storage-queue](https://pypi.org/project/azure-storage-queue): Queue storage client

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by sanchisingh01** [comment]
I ran into the same problems as you did, and i was able to get it running.
I didn't use the requirements.txt but this may be helpful, these instructions are Win 11 specific though, so keep that in mind:
I used **python ver 3.9.13,** you might wanna use this, because with other versions there are dependancy issues. 
ran the following commands in the virtual env:
pip install streamlit
pip install openai
pip install langchain
pip install python-dotenv
pip install tabulate
and the app runs fine, just that when i try asking questions the it says I've exceeded my limit of free usage. I guess other than that, the app runs fine.
